import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";
import { wrapper } from "@/redux/store";
import { getFilms } from "@/utils/api";
import { setFilms } from "@/redux/slices/films";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello bedolagi
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (ctx) => {
    try {
      // const films = await getFilms();
      // store.dispatch(setFilms(films));
      return { props: {} };
    } catch (err) {
      console.log(err);
      return { props: {} };
    }
  });
