import Head from "next/head";
import { GetServerSideProps } from "next";
import { wrapper } from "@/redux/store";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello bedolagi
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (ctx) => {
    try {
      // const films = await getFilms();
      // store.dispatch(setFilms(films));
      return { props: {} };
    } catch (err) {
      console.log(err);
      return { props: {} };
    }
  });
